import React, { useState } from "react";
import globalUniversity from "../assets/globalUniversity.jpg";
import { PhoneForwarded, Video } from "lucide-react";

const SkillCourse02 = () => {
  const [showContact, setShowContact] = useState(false);

  // === DATA: one provider (Glocal University) with many skill courses ===
  const glocalCourses = [
    "Glocal University Skill Course Icu Technician",
    "Glocal University Skill Course Hydraulic Excavator Operation & Maintenance",
    "Glocal University Skill Course Land Spacing Technician",
    "Glocal University Skill Course Jute Work/craft",
    "Glocal University Skill Course Irrigation Equipment Mechanic",
    "Glocal University Skill Course Interior Architecture",
    "Glocal University Skill Course Junior Plant Operator",
    "Glocal University Skill Course Iridology And Acupressure",
    "Glocal University Skill Course Interior And Exterior Architecture",
    "Glocal University Skill Course Integrative Alternative Therapy",
    "Glocal University Skill Course Integrated Spa Therapies",
    "Glocal University Skill Course Industrial Environmental Safety",
    "Glocal University Skill Course Indoor Technician",
    "Glocal University Skill Course Interior Decoration & Designing",
    "Glocal University Skill Course Land Survey",
    "Glocal University Skill Course Industrial Safety & Disaster Management",
    "Glocal University Skill Course Lab Assistant",
    "Glocal University Skill Course Kalariuzhichil",
    "Glocal University Skill Course Interior & Exterior Designing",
    "Glocal University Skill Course Java Programming",
    "Glocal University Skill Course J2ee",
    "Glocal University Skill Course Information Technology",
    "Glocal University Skill Course Laboratory Technician (horticultural)",
    "Glocal University Skill Course Industrial Safety",
    "Glocal University Skill Course Industrial Electronics Technology",
    "Glocal University Skill Course Internet Applications",
    "Glocal University Skill Course Interior Design And Visualization",
    "Glocal University Skill Course Improved Chula Making",
    "Glocal University Skill Course Hydraulic Mechanical Engineering",
    "Glocal University Skill Course Horticulture",
    "Glocal University Skill Course Honey Processing Technician",
    "Glocal University Skill Course Honey Bee Keeping Technician",
    "Glocal University Skill Course Home Science",
    "Glocal University Skill Course Home Network Management",
    "Glocal University Skill Course Home Network Assistant",
    "Glocal University Skill Course Horticulture Salesman",
    "Glocal University Skill Course Home Management And Geriatric Care, Residential & I.i.",
    "Glocal University Skill Course Home Management And Geriatric Care",
    "Glocal University Skill Course Industrial Safety Engineering",
    "Glocal University Skill Course Interior Designing",
    "Glocal University Skill Course Henna Making",
    "Glocal University Skill Course Hazard Analysis Critical Control Point",
    "Glocal University Skill Course Four Wheeler Mechanic (lmv)",
    "Glocal University Skill Course Forensic Odontology",
    "Glocal University Skill Course Hearing Impairment",
    "Glocal University Skill Course Greetings Card Making",
    "Glocal University Skill Course Generator Operation & Service Technology",
    "Glocal University Skill Course Garden Supervisor",
    "Glocal University Skill Course Hair Band Making",
    "Glocal University Skill Course Game Design",
    "Glocal University Skill Course Hatchery Operator",
    "Glocal University Skill Course Home Management (multiskilling And Residential)",
    "Glocal University Skill Course General Healthcare & Maternity Assistant",
    "Glocal University Skill Course Guasa Therapy & Art Of Foot Neurological Therapy",
    "Glocal University Skill Course Health Safety Environment & Management",
    "Glocal University Skill Course Gas Stove Technician",
    "Glocal University Skill Course Gardener (mali)",
    "Glocal University Skill Course Fork Lift Driving Cum Maintenance",
    "Glocal University Skill Course Glass Painting",
    "Glocal University Skill Course Hair Styling",
    "Glocal University Skill Course Heat Ventilation & Air Condition Engineering",
    "Glocal University Skill Course Hatchery Technician",
    "Glocal University Skill Course Gas Welder",
    "Glocal University Skill Course Holography And Acupuncture",
    "Glocal University Skill Course Heavy Crane Operation & Management",
    "Glocal University Skill Course Health, Safety & Environment Management",
    "Glocal University Skill Course Health Care Management",
    "Glocal University Skill Course Hair Dressing",
    "Glocal University Skill Course Food Technology",
    "Glocal University Skill Course Heavy Electrical Motor Winder",
    "Glocal University Skill Course Guidance And Counselling",
    "Glocal University Skill Course Food Safety",
    "Glocal University Skill Course Flowers And Plants Packaging Technician",
    "Glocal University Skill Course Floriculture & Landscaping Technology",
    "Glocal University Skill Course Florist Salesman",
    "Glocal University Skill Course Floriculture Technician",
    "Glocal University Skill Course Fisheries Technology",
    "Glocal University Skill Course Fisheries Survey Technician",
    "Glocal University Skill Course Fisheries Seed Production Technician",
    "Glocal University Skill Course Fisheries Feed Manufacturing Techniques",
    "Glocal University Skill Course Fish Bank Techniques",
    "Glocal University Skill Course Fisheries Feed Technician",
    "Glocal University Skill Course Fish Farmer",
    "Glocal University Skill Course Fire, Industrial & Environment Health Safety Mgmt",
    "Glocal University Skill Course Fisheries Field Technician",
    "Glocal University Skill Course Fire Technician",
    "Glocal University Skill Course Fire Safety & Security Management",
    "Glocal University Skill Course Fisheries Laboratory Technician",
    "Glocal University Skill Course Fire Fighting",
    "Glocal University Skill Course Fire Engineering& Industrial Safety Management",
    "Glocal University Skill Course Fire Engineering & Safety Management",
    "Glocal University Skill Course Fire Engineering",
    "Glocal University Skill Course Fire And Construction Safety Management",
    "Glocal University Skill Course Fire Man Technician",
    "Glocal University Skill Course Fire & Safety Methods",
    "Glocal University Skill Course Fire & Safety Engineering Techniques",
    "Glocal University Skill Course Financial Management Software",
    "Glocal University Skill Course Fengshui And Acupuncture",
    "Glocal University Skill Course Fancy Articles Making",
    "Glocal University Skill Course Eye Technician",
    "Glocal University Skill Course Environment Safety Engineering",
    "Glocal University Skill Course Fire & Safety Engineering",
    "Glocal University Skill Course Entrepreneurship Skills Development",
    "Glocal University Skill Course Employability Skills",
    "Glocal University Skill Course Domestic House Keeping",
    "Glocal University Skill Course Elementary Education, advanced",
    "Glocal University Skill Course Electronic Chock Maker",
    "Glocal University Skill Course Embedded System & Plc Technician",
    "Glocal University Skill Course Elementary Education",
    "Glocal University Skill Course Emergency Medical Services",
    "Glocal University Skill Course Electronics Technician",
    "Glocal University Skill Course Electrician",
    "Glocal University Skill Course Electrical Safety",
    "Glocal University Skill Course Electrical Qc",
    "Glocal University Skill Course Embedded System",
    "Glocal University Skill Course Electrical Power Drives Technician",
    "Glocal University Skill Course Emergency Light Technician",
    "Glocal University Skill Course Electrical & Electronics Technology",
    "Glocal University Skill Course Eeg & Emg Technology",
    "Glocal University Skill Course Early Childhood Special Education",
    "Glocal University Skill Course Dry Cleaning",
    "Glocal University Skill Course E C G Technician",
    "Glocal University Skill Course Early Childhood Care And Education",
    "Glocal University Skill Course Electronic O e",
    "Glocal University Skill Course Drawing And Water Colour Painting",
    "Glocal University Skill Course Domestic Helper",
    "Glocal University Skill Course Domestic Electronic Equipment Servicing",
    "Glocal University Skill Course Domestic Electrical Motor Winder",
    "Glocal University Skill Course Doll Making",
    "Glocal University Skill Course Doa (ms -o e Only)",
    "Glocal University Skill Course Diploma In Graphics",
    "Glocal University Skill Course Diploma In Computer Technology",
    "Glocal University Skill Course Diploma In Acupuncture",
    "Glocal University Skill Course Diesel Mechanism (stationery & Mobile Engines)",
    "Glocal University Skill Course Diesel Fuel System Service Mechanic",
    "Glocal University Skill Course Diabetology",
    "Glocal University Skill Course Diabetic Care & Diet By Ayurveda",
    "Glocal University Skill Course Dietician",
    "Glocal University Skill Course Desktop Publishing",
    "Glocal University Skill Course Design Painter",
    "Glocal University Skill Course Dental Technician",
    "Glocal University Skill Course Dental Lab Technician",
    "Glocal University Skill Course Dental Hygienist",
    "Glocal University Skill Course Data Science",
    "Glocal University Skill Course Dental Assistant",
    "Glocal University Skill Course De-addiction By Acupuncture",
    "Glocal University Skill Course Dairy Laboratory Technician",
    "Glocal University Skill Course Computer Faculty Training",
    "Glocal University Skill Course Dairy Products Processing",
    "Glocal University Skill Course Ct Scan Technician",
    "Glocal University Skill Course Creche And Pre-school Management",
    "Glocal University Skill Course Consumer Electronics Maintenance",
    "Glocal University Skill Course Dairy Technician",
    "Glocal University Skill Course Computer Technology",
    "Glocal University Skill Course Computer Science",
    "Glocal University Skill Course Computer Hardware Maintenance",
    "Glocal University Skill Course Concrete Ndt",
    "Glocal University Skill Course Computer Hardware & Networking",
    "Glocal University Skill Course Cvts Technology",
    "Glocal University Skill Course Dairy Store Technician",
    "Glocal University Skill Course Cosmetology And Beauty Parlour Management",
    "Glocal University Skill Course Computer In Retail Shop",
    "Glocal University Skill Course Computer Tc",
    "Glocal University Skill Course Data Entry Operator",
    "Glocal University Skill Course Cosmetology & Beauty Parlour Management",
    "Glocal University Skill Course Construction Management",
    "Glocal University Skill Course Critical Care Management",
    "Glocal University Skill Course Construction Safety",
    "Glocal University Skill Course Computer Hardware Maintenance And Network Engineering",
    "Glocal University Skill Course Computer Applications",
    "Glocal University Skill Course Dairy Technology",
    "Glocal University Skill Course Crane Operation & Maintenance",
    "Glocal University Skill Course Construction Safety Management",
    "Glocal University Skill Course Corel Draw",
    "Glocal University Skill Course Dairy Dock Technician",
    "Glocal University Skill Course Computer Python Programming",
    "Glocal University Skill Course Communication Skills Trainer",
    "Glocal University Skill Course Cold Storage Technology",
    "Glocal University Skill Course Communication Skills And English Language",
    "Glocal University Skill Course Cobol Programming",
    "Glocal University Skill Course Civil Construction Supervisor",
    "Glocal University Skill Course Chick Sexer",
    "Glocal University Skill Course Communication Skills Development",
    "Glocal University Skill Course Cold Storage Technology",
    "Glocal University Skill Course Coir Items Making",
    "Glocal University Skill Course Coconut- By Products Processing Technician",
    "Glocal University Skill Course Cloth Bag Making",
    "Glocal University Skill Course Clock & Watch Repair Technician",
    "Glocal University Skill Course Clerical Job In Computerised O e",
    "Glocal University Skill Course Classroom Teaching Instructional Strategies",
    "Glocal University Skill Course Classical Acupuncture",
    "Glocal University Skill Course Cnc Programmer",
    "Glocal University Skill Course Clinical Laboratory Technology",
    "Glocal University Skill Course Civil Engineering Techniques",
    "Glocal University Skill Course Civil Engineering",
    "Glocal University Skill Course Civil Draughts Man",
    "Glocal University Skill Course Chip Level System",
    "Glocal University Skill Course Child Remedial Education",
    "Glocal University Skill Course Chalk Pieces And Candle Making",
    "Glocal University Skill Course Certified Health Safety & Environment Engineer",
    "Glocal University Skill Course Certificate In Vb.net",
    "Glocal University Skill Course Certificate In Tv Mechanism",
    "Glocal University Skill Course Chemical Plant Processing Safety & Management",
    "Glocal University Skill Course Certificate In Oracle",
    "Glocal University Skill Course Certificate In Operations Of Computer In Retail Shops",
    "Glocal University Skill Course Certificate In Obesity Care By Ayurveda",
    "Glocal University Skill Course Certificate In Mobile Phone Technology (course Code: Ccs009)",
    "Glocal University Skill Course Certificate In Agriculture Science",
    "Glocal University Skill Course Certificate In Clerical Jobs In Computerised OOfe",
    "Glocal University Skill Course Certificate In Fire & Safety Engineering Techniques",
    "Glocal University Skill Course Certificate In Computer Hardware Maintenance",
    "Glocal University Skill Course Certificate In Industrial Electronics",
    "Glocal University Skill Course Certificate In Ayurvedic Food Science And Cooking",
    "Glocal University Skill Course Cable Tv Network Technician",
    "Glocal University Skill Course Bss Diploma In Invertor, Ups Technology",
    "Glocal University Skill Course C Programming",
    "Glocal University Skill Course Building Design",
    "Glocal University Skill Course Cctv Technician",
    "Glocal University Skill Course Bss Advanced Diploma In Information Technology",
    "Glocal University Skill Course Car A/c Mechanic",
    "Glocal University Skill Course Building Supervisor",
    "Glocal University Skill Course Boat Construction Technology",
    "Glocal University Skill Course Ayurvedic Lifestyle Coach",
    "Glocal University Skill Course Backhoe Loader Operation & Maintenance",
    "Glocal University Skill Course Cashier",
    "Glocal University Skill Course Building Quality Management",
    "Glocal University Skill Course Bss Diploma In O Shoe Safety",
    "Glocal University Skill Course Cnc Vertical Milling Machine Operation",
    "Glocal University Skill Course Chef Operation",
    "Glocal University Skill Course Bss Equipment Technician",
    "Glocal University Skill Course Bss Tsa (temp Service Advisor)",
    "Glocal University Skill Course Construction And Building Construction Technician",
    "Glocal University Skill Course Cargo Container Freight Crane Operator",
    "Glocal University Skill Course Cabin Steward",
    "Glocal University Skill Course Business Sustainability & Hospitality Strategy Development",
    "Glocal University Skill Course Business Analytics",
    "Glocal University Skill Course Plant Protection And Pesticides Management",
    "Glocal University Skill Course Nursery Education",
    "Glocal University Skill Course Montessori And Child Education",
    "Glocal University Skill Course Medicinal Plants Processing",
    "Glocal University Skill Course Four Wheeler Mechanism",
    "Glocal University Skill Course Food Preservation Technology",
    "Glocal University Skill Course Early Education System",
    "Glocal University Skill Course Crops Production",
    "Glocal University Skill Course Automobile Engineering",
    "Glocal University Skill Course Agro-based Industrial Management",
    "Glocal University Skill Course X-ray Technology",
    "Glocal University Skill Course X-ray Technician",
    "Glocal University Skill Course Wire Bag Knitting",
    "Glocal University Skill Course Horticulture Supervisor Training",
    "Glocal University Skill Course Heavy Motor Vehicle Mechanism",
    "Glocal University Skill Course X Ray & Imaging Technology",
    "Glocal University Skill Course Windows/linux",
    "Glocal University Skill Course Wet Cleaning Technician",
    "Glocal University Skill Course Wellness Therapy And Management",
    "Glocal University Skill Course Agriculture Science",
    "Glocal University Skill Course Web Designing",
    "Glocal University Skill Course Wax Decorative Articles Making",
    "Glocal University Skill Course Water Shed Protection And Management",
    "Glocal University Skill Course Vocational Instructor (crop Production)",
    "Glocal University Skill Course Visual Design & Communication",
    "Glocal University Skill Course Visual C++",
    "Glocal University Skill Course Inspector Of Auto Manufacturing Industry",
    "Glocal University Skill Course Visual Effects",
    "Glocal University Skill Course Stenography",
    "Glocal University Skill Course Spoken English",
    "Glocal University Skill Course Veterinary Sciences",
    "Glocal University Skill Course Umbrella Assembling",
    "Glocal University Skill Course Varmaniam Massage Therapy",
    "Glocal University Skill Course Transport Of Hazardous And Dangerous Goods By Road",
    "Glocal University Skill Course User Interface And User Experience (UI/UX)",
    "Glocal University Skill Course Veterinary Laboratory Technician",
    "Glocal University Skill Course Technology In Teaching (CPTT)",
    "Glocal University Skill Course Structural Technician",
    "Glocal University Skill Course Sub Fire Station O er",
    "Glocal University Skill Course Vanilla Cultivation Plant Protection",
    "Glocal University Skill Course Thermocol Decorator",
    "Glocal University Skill Course Tibb Acupuncture",
    "Glocal University Skill Course Stress Management By Acupuncture",
    "Glocal University Skill Course Steam Pressing Technician",
    "Glocal University Skill Course Spray Painter",
    "Glocal University Skill Course Varma & Massage Science",
    "Glocal University Skill Course Vermiculture Technician",
    "Glocal University Skill Course Ultra Sonography Technician",
    "Glocal University Skill Course Tally ERP 9",
    "Glocal University Skill Course Two Wheeler Mechanic",
    "Glocal University Skill Course Trichology",
    "Glocal University Skill Course Veterinary Inspector",
    "Glocal University Skill Course Vehicle Surveyor",
    "Glocal University Skill Course Trauma Care & Casualty Technology",
    "Glocal University Skill Course Visual Basic",
    "Glocal University Skill Course Virtual Teaching",
    "Glocal University Skill Course Veterinary Pharmacy",
    "Glocal University Skill Course Traditional Acupuncture & Sujok Acupuncture",
    "Glocal University Skill Course Tractor And Power Tiller Mechanic",
    "Glocal University Skill Course Toys (plaster Of Paris)",
    "Glocal University Skill Course Thai Massage And Treatments",
    "Glocal University Skill Course Telephone Technician",
    "Glocal University Skill Course Sujok Acupuncture",
    "Glocal University Skill Course Stabilizer Maker",
    "Glocal University Skill Course Special Education (deaf Blindness)",
    "Glocal University Skill Course Sustainable Environmental Management",
    "Glocal University Skill Course Terracotta Work",
    "Glocal University Skill Course Vision Care Technician",
    "Glocal University Skill Course Spa Massage By Ayurveda",
    "Glocal University Skill Course Spa Management",
    "Glocal University Skill Course Soil Conservation Technician",
    "Glocal University Skill Course Soil Conservation & Rural Construction Technology",
    "Glocal University Skill Course Software Applications",
    "Glocal University Skill Course Soft Toys Making",
    "Glocal University Skill Course Sisulekshmy Nursery Education",
    "Glocal University Skill Course Sign Board Writer",
    "Glocal University Skill Course Shiatsu Massage And Aromatherapy",
    "Glocal University Skill Course Spawn Producing Techniques",
    "Glocal University Skill Course Sheet Metal Works & Tinkering",
    "Glocal University Skill Course Sheet Metal Fabricator",
    "Glocal University Skill Course Sheet Metal & Fabrication",
    "Glocal University Skill Course Sewing Machine Technician",
    "Glocal University Skill Course Senior Secondary Level Typewriting English",
    "Glocal University Skill Course Semi-permanent Makeup & Cosmetic Micropigmentation",
    "Glocal University Skill Course Skilled FRP Worker",
    "Glocal University Skill Course Self Grooming & Bridal Make Up",
    "Glocal University Skill Course Seed Production Technician",
    "Glocal University Skill Course Secretarial Practice",
    "Glocal University Skill Course Primary Education",
    "Glocal University Skill Course Radio & TV Assembler",
    "Glocal University Skill Course Refrigeration, Heat Ventilation & Air Condition Engg",
    "Glocal University Skill Course Radio And Television Service",
    "Glocal University Skill Course Public Relations O er",
    "Glocal University Skill Course Psychological Guidance & Counseling",
    "Glocal University Skill Course Rubber Stamps Making",
    "Glocal University Skill Course Quantity Surveying & Billing Engineer In Civil Construction",
    "Glocal University Skill Course Pulmonary Function Test (PFT) Technician",
    "Glocal University Skill Course Primary Education, Advanced",
    "Glocal University Skill Course Rain Water Harvesting Technician",
    "Glocal University Skill Course Rural Management",
    "Glocal University Skill Course Rural Medical Care Provider",
    "Glocal University Skill Course Rexin Bag Making",
    "Glocal University Skill Course Reflexology And Acupressure",
    "Glocal University Skill Course Purchasing & Store Keeping Technician",
    "Glocal University Skill Course Rehabilitation Psychology",
    "Glocal University Skill Course Receptionist",
    "Glocal University Skill Course Secondary Level Typewriting Tamil",
    "Glocal University Skill Course Refrigeration & Air Conditioning Engineering",
    "Glocal University Skill Course Preparatory Course In DTP",
    "Glocal University Skill Course Preparatory Course In CEO",
    "Glocal University Skill Course Poultry Health Inspector",
    "Glocal University Skill Course Plant Nursery Making",
    "Glocal University Skill Course Pre-school Education (DPSE)",
    "Glocal University Skill Course Power Inverter Technician",
    "Glocal University Skill Course Power Plant Engineering, Safety & Technology",
    "Glocal University Skill Course Poultry Pharmaceutical Salesmanship",
    "Glocal University Skill Course Pre-school And Primary Education (DPPE)",
    "Glocal University Skill Course Predictive Maintenance",
    "Glocal University Skill Course Poultry Management",
    "Glocal University Skill Course Poultry Laboratory Technician",
    "Glocal University Skill Course Preservation Technician (horticultural)",
    "Glocal University Skill Course Pre-primary Education",
    "Glocal University Skill Course Poultry Feed Technician",
    "Glocal University Skill Course Poultry Product Technician",
    "Glocal University Skill Course Poultry Feed Manufacturing Techniques",
    "Glocal University Skill Course Poultry Farmer",
    "Glocal University Skill Course Poultry Farm Record Keeper",
    "Glocal University Skill Course Pot Painting",
    "Glocal University Skill Course Post Diploma In Computer Hardware Maintenance",
    "Glocal University Skill Course Pollution Control Management",
    "Glocal University Skill Course Plant Protection Technician",
    "Glocal University Skill Course Plant Protection",
    "Glocal University Skill Course Plant Maintenance Technician",
    "Glocal University Skill Course Pituitary Bank Techniques",
    "Glocal University Skill Course Physiotherapy Technician",
    "Glocal University Skill Course Physiotherapy And Acupressure",
    "Glocal University Skill Course Physiotherapy & Ayurveda",
    "Glocal University Skill Course Pharmacy Profession & Community Health",
    "Glocal University Skill Course Personality Development",
    "Glocal University Skill Course Personality Trainer",
    "Glocal University Skill Course Petro Chemical Process Safety & Engineering",
    "Glocal University Skill Course PDM-Vibration Analysis",
    "Glocal University Skill Course Personal Secretaryship",
    "Glocal University Skill Course Perfume Making",
    "Glocal University Skill Course Poultry Technology",
    "Glocal University Skill Course Physician Assistant",
    "Glocal University Skill Course PDM-Ultrasound",
    "Glocal University Skill Course PDM-Infrared Thermography",
    "Glocal University Skill Course Paper Covers Making",
    "Glocal University Skill Course Panchakarma & Massage Therapy",
    "Glocal University Skill Course Operation Theatre Management",
    "Glocal University Skill Course O e Assistantship",
    "Glocal University Skill Course O e Computer Operator",
    "Glocal University Skill Course Ornamental Fish Cultivation And Management",
    "Glocal University Skill Course Operation & Maintenance Of Hydraulic Heavy Machineries.",
    "Glocal University Skill Course Operation & Maintenance Of Heavy Machineries (crane)",
    "Glocal University Skill Course Optometry",
    "Glocal University Skill Course Open O e",
    "Glocal University Skill Course Operation & Maintenance Of Heavy Machineries (fork Lift)",
    "Glocal University Skill Course Occupational Safety & Health",
    "Glocal University Skill Course Operation & Maintenance Of Heavy Machineries (hydraulic)",
    "Glocal University Skill Course Offshore, Rig, Oil And Gas Safety Engineering",
    "Glocal University Skill Course O e Practice Management",
    "Glocal University Skill Course Mushroom Cultivation And Protection",
    "Glocal University Skill Course Multimedia",
    "Glocal University Skill Course Multimedia Programming",
    "Glocal University Skill Course Microsoft",
    "Glocal University Skill Course Occupational Health",
    "Glocal University Skill Course Ophthalmic Assistant",
    "Glocal University Skill Course Oil Painting",
    "Glocal University Skill Course Nail Technology",
    "Glocal University Skill Course Operation & Maintenance Of Heavy Machineries",
    "Glocal University Skill Course O e Accounting",
    "Glocal University Skill Course Operation Theatre Technology",
    "Glocal University Skill Course Occupational Safety, Health & Environmental Mgmt",
    "Glocal University Skill Course Palliative Care Therapist (back Hoe Loader)",
    "Glocal University Skill Course Nature Cure Beauty",
    "Glocal University Skill Course Multimedia Animation",
    "Glocal University Skill Course Panchakarma",
    "Glocal University Skill Course Ortho & Trauma Care Technician",
    "Glocal University Skill Course Oil And Gas Safety Engineering",
    "Glocal University Skill Course Occupational Health, Safety, Environment & Risk Mgmt",
    "Glocal University Skill Course Net And Gear Technician",
    "Glocal University Skill Course Montessori And Child Education",
    "Glocal University Skill Course Mobile Phone Technician",
    "Glocal University Skill Course Mental Retardation",
    "Glocal University Skill Course Mehandi Application",
    "Glocal University Skill Course Montessori And Grade Level Education",
    "Glocal University Skill Course MRI Scan Technician",
    "Glocal University Skill Course Montessori, Kindergarten & Nursery Education",
    "Glocal University Skill Course Montessori And Primary Education",
    "Glocal University Skill Course Mid Level Ophthalmic Personnel",
    "Glocal University Skill Course Medical Psychology",
    "Glocal University Skill Course Medical Laboratory Technology",
    "Glocal University Skill Course Medical Equipment Technology",
    "Glocal University Skill Course Medical Equipment Technician",
    "Glocal University Skill Course Mat Making",
    "Glocal University Skill Course Masseura",
    "Glocal University Skill Course Maseur & Panchakarma",
    "Glocal University Skill Course Manufacturing Of Jute Bags, Door Mats, Table Mats.",
    "Glocal University Skill Course Medical Transcription",
    "Glocal University Skill Course Magneto Therapy And Acupressure",
    "Glocal University Skill Course Medical Transcript Technician",
    "Glocal University Skill Course Livestock Technician",
    "Glocal University Skill Course Medicinal Plant Cultivation Technology",
    "Glocal University Skill Course Livestock Dairy Supervisor",
    "Glocal University Skill Course Mental Retardation",
    "Glocal University Skill Course Medical Record Sciences",
    "Glocal University Skill Course Livestock Inspector",
    "Glocal University Skill Course Mechanical Fitter Cum CNC Machine Operator",
    "Glocal University Skill Course Land Survey Assistant",
    "Glocal University Skill Course Learning Disability",
    "Glocal University Skill Course Leather Work",
    "Glocal University Skill Course Laundry & Wet Cleaning Technician",
    "Glocal University Skill Course Landscaping Technician",
    "Glocal University Skill Course Land Survey Engineering",
    "Glocal University Skill Course Land Surveying (using Total Station & GPS)",
    "Glocal University Skill Course Laproscopy Assistant",
    "Glocal University Skill Course Laptop Hardware & Wi-Fi Technology",
    "Glocal University Skill Course Light Motor Vehicle Mechanism",
    "Glocal University Skill Course Ledger Clerk",
    "Glocal University Skill Course Land Survey & Documentation",
    "Glocal University Skill Course Milk Chilling Centre Technician",
  ];

  const providers = [
    {
      name: "Glocal University — Skill Courses",
      description:
        "Explore a large catalog of hands-on, job-ready programs across healthcare, engineering, IT, design, safety, and more.",
      logo: globalUniversity,
      courses: glocalCourses,
    },
  ];

  const handleQuickCall = () => {
    window.location.href = "tel:+917887881060";
  };

  const handleWhatsApp = () => {
    window.open("https://wa.me/917887881060", "_blank"); // opens WhatsApp chat
  };

  return (
    <div className="min-h-screen  text-[#333] mb-5">
      {/* Header */}
      

      {/* Main Content */}
      <div className="mx-auto my-5 w-full max-w-7xl px-4 flex flex-col md:flex-row gap-2">
        {/* Right (Provider & Course List) */}
        <div className="flex-1 bg-white rounded-xl p-6 shadow-sm">
          {providers.map((uni, index) => (
            <div key={index} className="university-card">
              <div className="uni-header-card flex items-center gap-3 text-left">
                <img
                  src={uni.logo}
                  alt={uni.name}
                  className="w-[160px] h-auto object-contain mr-5 rounded-md bg-white"
                />
                <div>
                  <h2 className="m-0 text-xl md:text-2xl font-semibold text-[#111]">
                    {uni.name}
                  </h2>
                  <p className="text-sm text-[#777]">{uni.description}</p>
                </div>
              </div>

              <hr className="my-4 border-t border-[#eee]" />

              <div className="flex items-center justify-center my-4">
            <div className="flex-grow border-t border-[#3E96F4]"></div>
            <span className="px-3 text-xl font-semibold text-[#3E96F4] bg-white">
              Specializations
            </span>
            <div className="flex-grow border-t border-[#3E96F4]"></div>
          </div>

              <div className="mt-4 max-h-[70vh] overflow-auto rounded-lg border border-[#eee]">
                <table className="w-full border-collapse">
                  <thead className="sticky top-0">
                    <tr>
                      <th className="border border-[#eee] bg-[#f8f8f8] px-3 py-3 text-left font-semibold">
                        Course Name
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {uni.courses.map((course, i) => (
                      <tr key={i} className="odd:bg-white even:bg-[#fafafa]">
                        <td className="border border-[#eee] px-3 py-3 text-left">
                          {course}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default SkillCourse02;
